<!-- Swiper -->
<div class="banner">
    <div class="swiper-container">
        <div class="swiper-wrapper">
            <div class="swiper-slide "><img class="img-responsive" src="http://i.kaikeba.com/149213750111522074"/></div>
            <div class="swiper-slide"><img class="img-responsive" src="http://i.kaikeba.com/149483886320427004"/></div>
            <div class="swiper-slide"><img class="img-responsive" src="http://i.kaikeba.com/149274205973428585"/></div>
            <div class="swiper-slide"><img class="img-responsive" src="http://i.kaikeba.com/149432809521239739"/></div>
            <div class="swiper-slide"><img class="img-responsive" src="http://i.kaikeba.com/147204897864254826"/></div>
            <div class="swiper-slide"><img class="img-responsive" src="http://i.kaikeba.com/147204890968063573"/></div>
        </div>
        <!-- Add Pagination -->
        <div class="swiper-pagination"></div>
           <!-- 如果需要导航按钮 -->
       <!-- <div class="swiper-button-prev"></div>
        <div class="swiper-button-next"></div> -->
    </div>
</div>