<section class="slide" {{"style=background-image:url("+course.data.pic+")"}}>
    <div class="wrap">
        <img class="icon" src="/public/pic/img_js_banner_kectb@2x.png" width="140px" height="140px">
        <h2 class="name">{{course.data.name}}</h2>
        <p class="des">
            {{course.data.description}}        </p>
        <a  href="http://student.kaikeba.com/course/16/path"  class="btn dashed-opt" target="_blank">免费试听</a>
        <a  href="/course/16#instant_signup"  class="btn solid-opt">参加就业班</a>
    </div>
</section>